//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieFrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieCmt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieCmt()
        {
            this.Cmt_ImageList = new HashSet<Cmt_ImageList>();
        }
    
        public int MovieCmt_ID { get; set; }
        public int Movie_ID { get; set; }
        public int Member_ID { get; set; }
        public string Title { get; set; }
        public int Rate { get; set; }
        public string Text { get; set; }
        public System.DateTime Created_Time { get; set; }
        public Nullable<System.DateTime> Edited_Time { get; set; }
        public bool Visible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cmt_ImageList> Cmt_ImageList { get; set; }
        public virtual Member Member { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
