//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieFrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.MovieCmts = new HashSet<MovieCmt>();
            this.MemberActions = new HashSet<MemberAction>();
            this.MovieActorsLists = new HashSet<MovieActorsList>();
            this.MovieCountriesLists = new HashSet<MovieCountriesList>();
            this.MovieDirectorsLists = new HashSet<MovieDirectorsList>();
            this.MovieImagesLists = new HashSet<MovieImagesList>();
            this.MovieLanguagesLists = new HashSet<MovieLanguagesList>();
            this.MovieTypesLists = new HashSet<MovieTypesList>();
            this.MovieTypesLists1 = new HashSet<MovieTypesList>();
            this.Sessions = new HashSet<Session>();
        }
    
        public int Movie_ID { get; set; }
        public Nullable<int> Series_ID { get; set; }
        public string MovieNameCht { get; set; }
        public string MovieNameEng { get; set; }
        public System.DateTime MovieScheduleStart { get; set; }
        public System.DateTime MovieScheduleEnd { get; set; }
        public Nullable<int> MovieShowLength { get; set; }
        public Nullable<int> Rating_ID { get; set; }
        public string MovieInteroduce { get; set; }
        public string MovieTrailerLink { get; set; }
        public byte[] MoviePoster { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieCmt> MovieCmts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberAction> MemberActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieActorsList> MovieActorsLists { get; set; }
        public virtual MovieRating MovieRating { get; set; }
        public virtual Series Series { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieCountriesList> MovieCountriesLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieDirectorsList> MovieDirectorsLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieImagesList> MovieImagesLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieLanguagesList> MovieLanguagesLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTypesList> MovieTypesLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTypesList> MovieTypesLists1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
