//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieFrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderStatusLogs = new HashSet<OrderStatusLog>();
        }
    
        public int Order_ID { get; set; }
        public int Session_ID { get; set; }
        public int Member_ID { get; set; }
        public int PayType_ID { get; set; }
        public Nullable<int> CreditCardType_ID { get; set; }
        public Nullable<int> Coupon_ID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual CreditCardType CreditCardType { get; set; }
        public virtual PayType PayType { get; set; }
        public virtual Session Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStatusLog> OrderStatusLogs { get; set; }
    }
}
