//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieFrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductsType()
        {
            this.ReceiptDetails = new HashSet<ReceiptDetail>();
        }
    
        public int product_ID { get; set; }
        public string product_Name { get; set; }
        public int product_Price { get; set; }
        public byte[] Image { get; set; }
        public string ImagePath { get; set; }
        public string Introduce { get; set; }
        public int Category_ID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDetail> ReceiptDetails { get; set; }
    }
}
